version: "3.3"
services:
  nestjs:
    build: .
    image: car-server
    ports:
     - "4343:4343"
    networks:
      - app
  mongodb:
    image: mongo
    ports:
     - "27017-27019:27017-27019"
    networks:
     - app

networks: 
  app:
